services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # pokenext-redis:
  #   build:
  #     context: ../pokenext-redis
  #   ports:
  #     - "4006:4006"
  #   depends_on:
  #     - redis

volumes:
  mongo_data:
